[package]
name = "driver"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = {git = "https://github.com/slint-ui/slint", default-features = false, features = ["renderer-software", "compat-1-2", "std"]}

[target.'cfg(unix)'.dependencies]
evdev = "0"
linuxfb = "0"
memmap = "0"